"""Shared B2 wire, budget, and generation/grace contract for server and host."""

from dataclasses import asdict, dataclass
from enum import IntEnum
import struct


@dataclass(frozen=True)
class TunnelContract:
    protocol_version: int = 1
    minimum_version: int = 1
    max_frame: int = 64 * 1024
    stream_credit: int = 256 * 1024
    max_streams: int = 32
    host_budget: int = 4 * 1024 * 1024
    process_budget: int = 64 * 1024 * 1024
    control_reserve: int = 64 * 1024
    max_text: int = 65535
    ping_seconds: int = 20
    dead_seconds: int = 50
    grace_seconds: int = 30
    reconnect_initial_seconds: float = 0.5
    reconnect_active_cap_seconds: int = 5
    reconnect_idle_cap_seconds: int = 30


CONTRACT = TunnelContract()
HEADER = struct.Struct("!BQII")
MAX_PAYLOAD = CONTRACT.max_frame - HEADER.size


class ProtocolError(ValueError):
    pass


class FrameKind(IntEnum):
    OPEN = 1
    ACK = 2
    DATA = 3
    CREDIT = 4
    FIN = 5
    RESET = 6


@dataclass(frozen=True)
class Frame:
    kind: FrameKind
    epoch: int
    stream_id: int
    payload: bytes = b""

    def encode(self) -> bytes:
        if not 0 < self.epoch < 2**64 or not 0 < self.stream_id < 2**32:
            raise ProtocolError("Invalid epoch or stream id")
        if len(self.payload) > MAX_PAYLOAD:
            raise ProtocolError("Oversize frame")
        if self.kind in {FrameKind.OPEN, FrameKind.ACK, FrameKind.CREDIT}:
            if (
                len(self.payload) != 4
                or not 0 < struct.unpack("!I", self.payload)[0] <= CONTRACT.stream_credit
            ):
                raise ProtocolError("Invalid credit")
        elif self.kind in {FrameKind.FIN, FrameKind.RESET} and self.payload:
            raise ProtocolError("Control frame has payload")
        elif self.kind == FrameKind.DATA and not self.payload:
            raise ProtocolError("Empty data frame")
        try:
            kind = FrameKind(self.kind)
        except ValueError as error:
            raise ProtocolError("Unknown frame") from error
        return HEADER.pack(kind, self.epoch, self.stream_id, len(self.payload)) + self.payload

    @classmethod
    def decode(cls, data: bytes) -> "Frame":
        if not HEADER.size <= len(data) <= CONTRACT.max_frame:
            raise ProtocolError("Invalid frame size")
        kind, epoch, stream_id, length = HEADER.unpack_from(data)
        if len(data) != HEADER.size + length:
            raise ProtocolError("Invalid frame length")
        try:
            frame = cls(FrameKind(kind), epoch, stream_id, data[HEADER.size :])
        except ValueError as error:
            raise ProtocolError("Unknown frame") from error
        frame.encode()
        return frame


def reconnect_delay(attempt: int, *, active: bool, random_value: float) -> float:
    cap = CONTRACT.reconnect_active_cap_seconds if active else CONTRACT.reconnect_idle_cap_seconds
    nominal = min(cap, CONTRACT.reconnect_initial_seconds * 2 ** min(max(attempt, 0), 16))
    return min(cap, nominal * (0.8 + 0.4 * min(max(random_value, 0), 1)))


def protocol_document() -> str:
    table = "\n".join(f"| {name} | {value} |" for name, value in asdict(CONTRACT).items())
    return f"""# Host tunnel protocol (B2)

Generated by `python -m artemis.runtime.host_protocol`. Do not edit the constants here.

| Constant | Value |
| --- | --- |
{table}

One authenticated `/api/agent/connect` WebSocket carries JSON session/heartbeat
messages and binary mux frames. Binary header: big-endian `!BQII` (kind,
64-bit connection epoch, 32-bit stream id, payload length), followed by payload.
The frame limit includes its 17-byte header. OPEN=1, ACK=2, DATA=3, CREDIT=4,
FIN=5, RESET=6. OPEN/ACK grant a 4-byte initial receive window; CREDIT returns
consumed bytes. FIN is half-close, ordered after queued DATA. RESET aborts both
directions. Stream ids are positive, monotonic, and never reused within an epoch.
Only the server opens streams; each OPEN targets the host's local adb server.
The server's allowlist gateway checks nested transport and service requests.

Generation/grace contract for CHE-1108 and B3:
- The authenticated registry generation is the frame epoch and endpoint generation.
- A disconnect immediately unregisters and closes its loopback listener and streams.
  Reconnect tries that host's saved loopback port while bound runs remain.
  With no bound run or if the saved port cannot bind, it allocates a fresh port.
  Consumers must resolve the current endpoint after a port change; cached worker
  ports are not rewritten. Existing TCP streams are not replayed.
- `host_tunnels.reconnecting(host_id)` reports the fixed grace deadline for bound
  active runs. B2 publishes no forced loss outcome before that deadline; the
  Computers view reports `reconnecting`. Idle computers go offline immediately.
- A1 stores the grace deadline before B2 closes streams. Worker failures are
  deferred across processes, and the queue retains the run slot until resolution.
  Completion/cancellation remain immediate. Expired authentication interrupts
  immediately with `auth_expired`, without the network-loss grace.
- `host_tunnels.bind_run(host_id, session_id)` binds an immutable host identity.
- A new authenticated generation before expiry cancels loss for those bound runs.
  Stale disconnects cannot tear down a newer generation or restart its deadline.
- At expiry, bound runs settle through A1 with `host_disconnected`, exactly once.
  Committed completion/cancellation remains authoritative. Reconnect never changes
  a run's host/serial. TCP streams are not replayed into a new generation.
- Reconnect uses multiplicative jitter 0.8–1.2, hard-capped at the active/idle
  ceiling. Ping and silence detection use the same constants on both peers.

Host/process saturation resets only the overflowing stream, preserving control
traffic and the other streams. The 256 KiB advertised per-stream window does not
override the aggregate byte caps.
Host output is untrusted: binary frames and credits are validated before enqueue;
ADB length-prefixed text is bounded and UTF-8 decoded strictly. Devices lists and
track updates contain only shared serials. Unshare closes the selected streams.
Both gateways accept legacy `host:transport:<shared>` and modern
`host:tport:serial:<shared>`; the latter relays the raw 8-byte transport id after
OKAY. `host:features` and shared-serial `features`, `get-state`, `get-serialno`
and valid `wait-for-*` forms are supported. Shell v2 uses the `shell,` prefix.
Scoped forwarding, unshared/implicit transport selection and all other denied
services remain denied. Wait responses carry a second OKAY or a bounded FAIL.
With ARTEMIS_HOST_AGENT enabled, the bundled Uvicorn startup paths cap complete
WebSocket messages server-wide at max_frame before ASGI delivery, including
fragmented, UTF-8 and decompressed messages. Flag-off transport defaults stay unchanged.
Alternate ASGI launchers must configure the same transport-layer cap themselves.
The default-off `ARTEMIS_HOST_AGENT` gate governs listener creation and requests.
"""


if __name__ == "__main__":
    print(protocol_document(), end="")
